### ISSUE TITLE
Backend & pipeline crash with recent pySigma versions

### ISSUE THREAD

**Issue by jgubler** [7RedViolin/pySigma-backend-cortexxdr#15]
Hi there, thanks for publishing this backend!

Was experimenting around with it and noticed that it crashes with any recent pySigma versions, with the following traceback:

```python
Traceback (most recent call last):
  File "C:\Users\<REDACTED>\convert_to_xql.py", line 8, in <REDACTED>
    pipeline = CortexXDR_pipeline()
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\pipelines\cortexxdr\cortexxdr.py", line 364, in CortexXDR_pipeline
    return ProcessingPipeline(
           ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 15, in __init__
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\processing\pipeline.py", line 442, in __post_init__
    raise TypeError(
TypeError: Each item in a postprocessing pipeline must be a QueryPostprocessingItem - don't use processing classes directly!
```

Alternatively, if instead of using the pipeline, the `CortexXDRBackend` is imported directly, it crashes on import with the same error.
The error is fairly descriptive, so at the bottom of this issue, I've put a simple diff for it.

As you'll notice, the diff also makes another small change, changing the related transformation's return from `query, True` to `query`. That's because that bool isn't actually necessary, and leaving it in (once the prior error is fixed) will cause:

```python
Traceback (most recent call last):
  File "C:\Users\<REDACTED>\convert_to_xql.py", line 15, in <REDACTED>
    cortex_backend.convert_rule(rule)
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\conversion\base.py", line 203, in convert_rule
    finalized_queries = [  # 3. Postprocess generated query
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\conversion\base.py", line 204, in <listcomp>
    self.finalize_query(
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\conversion\base.py", line 1864, in finalize_query
    return super().finalize_query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\conversion\base.py", line 662, in finalize_query
    return self.last_processing_pipeline.postprocess_query(rule, backend_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\processing\pipeline.py", line 527, in postprocess_query
    query, applied = item.apply(self, rule, query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\processing\pipeline.py", line 385, in apply
    result = self.transformation.apply(pipeline, rule, query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\Lib\site-packages\sigma\pipelines\cortexxdr\cortexxdr.py", line 53, in apply
    if re.search(single_pattern, query): # for single value
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\<REDACTED>\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'tuple' (while finalizing query for rule None)
```

--

The diff that solves both:
```python
diff --git a/sigma/pipelines/cortexxdr/cortexxdr.py b/sigma/pipelines/cortexxdr/cortexxdr.py
index 979736d..80627c6 100644
--- a/sigma/pipelines/cortexxdr/cortexxdr.py
+++ b/sigma/pipelines/cortexxdr/cortexxdr.py
@@ -2,7 +2,7 @@ from typing import Union
 from sigma.pipelines.common import logsource_windows, windows_logsource_mapping
 from sigma.processing.transformations import ConditionTransformation, AddConditionTransformation, FieldMappingTransformation, DetectionItemFailureTransformation, RuleFailureTransformation, ChangeLogsourceTransformation, SetStateTransformation
 from sigma.processing.conditions import LogsourceCondition, ExcludeFieldCondition, RuleProcessingItemAppliedCondition
-from sigma.processing.pipeline import ProcessingItem, ProcessingPipeline
+from sigma.processing.pipeline import QueryPostprocessingItem, ProcessingItem, ProcessingPipeline
 from sigma.processing.postprocessing import QueryPostprocessingTransformation
 from sigma.rule import SigmaDetectionItem, SigmaDetection, SigmaRule
 from sigma.exceptions import SigmaTransformationError
@@ -71,7 +71,7 @@ class ReplaceIntegrityLevelQueryTransformation(QueryPostprocessingTransformation
         if output_type == 'json':
             query = json.loads(query)
 
-        return query, True
+        return query
 
 
 def CortexXDR_pipeline() -> ProcessingPipeline:
@@ -374,6 +374,9 @@ def CortexXDR_pipeline() -> ProcessingPipeline:
             *unsupported_rule_types,
         ],
         postprocessing_items=[
-            ReplaceIntegrityLevelQueryTransformation(),
+            QueryPostprocessingItem(
+                identifier=f'replace_integrity_level',
+                transformation=ReplaceIntegrityLevelQueryTransformation(),
+            ),
         ],
     )
\ No newline at end of file
```

I've tested the patched state with a number of local sigma rules, works flawlessly.

Would be great if you could apply this diff! I would've opened a pull request directly, but unfortunately you've not allowed that for this repository.

**Comment by 7RedViolin** [comment]
Thank you @jgubler for both identifying the issue and finding a solution! Sorry that PRs aren't able to be created directly - I'll see if I can get access fixed up for this repo. In the meantime, I'll be pushing out this change in version 0.1.4!
